### ISSUE TITLE
Spanish translation.

### ISSUE THREAD

**Issue by vidimus** [bbstucco/ADelicateSituationScenario#1]
Hello, @bbstucco 

I've got in mind the translation into Spanish of your scenario. Is there any chance for updating the scenario with a possible Spanish translation?

Thanks.

**Comment by bbstucco** [comment]
Hi. Are you asking me to translate it, or offering to translate it
yourself? I'm totally fine if someone wants to translate it.

**Comment by vidimus** [comment]
Hello, @bbstucco .

I'm offering for translating into Spanish. It wouldn't be right now, but soon (I've got other translation in the queue).

**Comment by bbstucco** [comment]
You are totally welcome to do so!

**Comment by vidimus** [comment]
Hello, @bbstucco . Do you have in mind updating or modifying your scenario? It's to have it in consideration before starting the translation. Plus, I would like to know if you are still available for updating / maintaining the scenario.

**Comment by vidimus** [comment]
Hello, @bbstucco  Are you available for updating the scenario with the translation and, in case of, fix some bugs?

**Comment by bbstucco** [comment]
Hi there.

My computer died a week ago and I lost everything. I would have to download
the scenario and go from there, which is doable. I would be available to do
some fixes, but only for another week or so. After that, I won't have
access to Valkyrie for some time.

David

**Comment by vidimus** [comment]
Hello, @bbstucco 

Translation is taking me a bit more than I expected. It's about 30.000 words. Have you consider sharing your repository with the Valkyrie's staff, i.e. @scrubbless? That way, he can update your scenario in case you can't and for me it will be a great help. Some users have done it previously and you maintain in all moment the IP, of course.

**Comment by bbstucco** [comment]
Sure! How do I do that? As I said, I no longer have access to Valkyrie. :(
I hope to regain it soon, but there is no timetable.

Is this something I would do on GitHub?

**Comment by vidimus** [comment]
Great, @bbstucco . Thanks a lot.

I've already commented this to @scrubbless, from Valkyrie's staff, to help you with the sharing process. I think it's quite simple to grant access to a repository adding someone as a collaborator

**Comment by scrubbless** [comment]
Hi @bbstucco !

I would happily maintain your scenario, I would only fix game breaking bugs and ensure that translations are added correctly.

To do this I will need collaborator access to your GitHub repotory.

To do this:

Open your repository and select "settings" from the menu. 
![Screenshot_20210109-121450_Chrome](https://user-images.githubusercontent.com/32058089/104091320-8ff7d580-5274-11eb-85fc-e8adfc199dbb.jpg)

Click Manage access and scroll down. You'll see a section to invite a collator. Hit invite and enter my username @scrubbless (scrubyuni@hotmail.com is my email).
![Screenshot_20210109-121509_Chrome](https://user-images.githubusercontent.com/32058089/104091369-e49b5080-5274-11eb-8128-9246405760e9.jpg)


I should get an invite and I can then assist.

**Comment by scrubbless** [comment]
I'll only need access to your published scenarios repo, I can get the most recent scenario files from the Valkyrie scenario explorer.

**Comment by bbstucco** [comment]
Scrubbles,

Thanks! Unfortunately, this may be a problem.

My PC died a couple of weeks ago and I'm on a Chromebook. So I don't have
access to my GitHub repository and can't download another one.

I'm open to suggestions, but I don't have access to a PC or Mac and
probably won't for a while. I don't think Chromebook can download the
software needed. :(

David (bbstucco)

**Comment by scrubbless** [comment]
You can do it from the web site.

Just go to:
https://github.com/bbstucco/ADelicateSituationScenario 

Click the setting menu option, then manage access and invite collaborator.

**Comment by bbstucco** [comment]
OK, I think I've done it. There were 3 scrubbles, but only one scrubbless.
Let me know if you got it or not. I may have invited someone else by
mistake. :)

**Comment by scrubbless** [comment]
Great thanks I got the invite!

**Comment by scrubbless** [comment]
@vidimus Have you started the translations?

**Comment by vidimus** [comment]
> @vidimus Have you started the translations?

Hello, @scrubbless and @bbstucco . First, thanks to both. And yes, I've started it. It's about 80% in fact, but there's a lot of work yet, reviewing and testing.

**Comment by vidimus** [comment]
@bbstucco Spanish translation is now in testing. It will take 1 or 2 weeks to be ready (a lot text and dialogues to review).

**Comment by bbstucco** [comment]
Great! Exciting!
